

export interface AdvertisementInterface {
  'id': number,
  'account_id': number,
  'group_id': number,
  'name': string,
  'code': string,
  'description': string,
  'priority': number,
  '_start': any,
  '_end': any,
  'type': string,
  'gender': string,
  'age_start': string,
  'age_end': string,
  'charging_type': string,
  'reach': number,
  'target': number,
  'budget': number,
  'spent': number,
  'isFeatured': number,
  'isNational': number,
  'os': string,
  'isActive': number,
  'isSelected' : number,
  'status': string,
  'created_at': string,
  'updated_at': string,
  'kotas': string,
  'witels': string,
  'regionals': string,
  'hours': any,
  'aps': any,
  'account': any,
  'group':any,
  'dataChecked': boolean,
  'price': number,
  '_impression': number,
  '_click' : number,
  '_view' : number
}
