export interface ApplicationInterface {
  id: number,
  dataChecked: boolean,
  username : string,
  phone : string,
  email : string,
  firstname : string,
  lastname : string,
  isActive : number,
  isBlock : number,
  password : string,
  access_group_id : number,
  access_group_ids : any,
  isEmailValid : number,
  isPhoneValid : number,
  birthdate : string,
  group : string,
  basicSalary : number,
  status : string,
  description : string
}
